import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/context/AuthContext";
import ConditionalLayout from "@/components/ConditionalLayout";
import { ThemeProvider } from "@/components/ThemeProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
    title: "Bookly-Ticket Booking Platform",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.png",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${outfit.className} antialiased`}
            >
                {/* <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                > */}
                <AuthProvider>
                    <ConditionalLayout>{children}</ConditionalLayout>
                    <Toaster richColors position="bottom-right" />
                </AuthProvider>
                {/* </ThemeProvider> */}
            </body>
        </html>
    );
}
